# Generated by Django 3.1.1 on 2020-10-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taking_img',
            name='file_name',
        ),
    ]
